### ISSUE TITLE
How to perform visualization of the PDM algorithm?

### ISSUE THREAD

**Issue by weiaiF** [autonomousvision/tuplan_garage#17]
I noticed the item related to visualization in the 'To Do' list. I'd like to inquire about when the corresponding visualization scripts will be made available. Thank you !

**Comment by DanielDauner** [comment]
Hi @weiaiF. To be transparent, the visualization scripts aren't currently on our immediate roadmap. We still want to add the visualization in the long run. In the meantime, you can visualize our planners using the regular nuBoard. 

Thank you for your understanding and interest!

**Comment by weiaiF** [comment]
Thanks for your reply, I will try the regular nuBoard.

**Comment by shuiyue1999** [comment]
Do I need to download all the data of the camera and lidar?
