### ISSUE TITLE
Qusetion about the result of PDM-Open with only the centerline input

### ISSUE THREAD

**Issue by weiaiF** [autonomousvision/tuplan_garage#18]
Hi, I am trying to reproduce the result in CoRL23 Table1 with only the centerline input. In the article, pdm-open achieved a score of 85 on the OLS, while my replication results only reached 21 in reduced_val14. I would like to know whether it is due to differences in my hyperparameter settings or if there are other issues. 

Changed pdm_open_model.py
```
self.planner_head = nn.Sequential(
            # nn.Linear(self.hidden_dim * 2, self.hidden_dim),
            nn.Linear(self.hidden_dim * 1, self.hidden_dim),
            nn.Dropout(0.1),
            nn.ReLU(),
            nn.Linear(self.hidden_dim, self.hidden_dim),
            nn.ReLU(),
            nn.Linear(self.hidden_dim, trajectory_sampling.num_poses * len(SE2Index)),
        )
# planner_features = torch.cat([state_encodings, centerline_encodings], dim=-1)
planner_features = centerline_encodings
```

![pdm_open_only_with_centerline_input](https://github.com/autonomousvision/tuplan_garage/assets/72204912/59089029-484e-46c6-826d-2c625ce7d728)

**Comment by DanielDauner** [comment]
Hi @weiaiF. The ablation in Tab. 1 without the ego history does include the current ego state at t=0. Thus, we only drop past states. Sorry for the confusion! The camera-ready version is more explicit on this.
