### ISSUE TITLE
Do I need to download all the data of the camera and lidar?

### ISSUE THREAD

**Issue by shuiyue1999** [autonomousvision/tuplan_garage#21]

**Comment by DanielDauner** [comment]
Thanks for your interest in our project!

You don’t need to download any camera or lidar data. For testing our planners with Val14, you need to download the validation set (~100GiB). If you want to train motion planners in nuPlan, you need the training files (~1Tib). Note that the files will significantly expand after unzipping. You can also use the mini split when starting with nuPlan.

**Comment by shuiyue1999** [comment]
I get it, thank you!

**Comment by DanielDauner** [comment]
Awesome! Feel free to re-open if you have further questions!
