### ISSUE TITLE
Updated checkpoints for urban driver and PDM open missing

### ISSUE THREAD

**Issue by HenryDykhne** [autonomousvision/tuplan_garage#25]
Hello,

I was wondering when the updated versions of the checkpoints at this link (https://drive.google.com/drive/folders/1LLdunqyvQQuBuknzmf7KMIJiA2grLYB2) would be uploaded to be compatible with the renamed version of tuplan garage.

**Comment by CristianGariboldi** [comment]
Hi Henry,
actually I am using them right now with the renamed version of tuplan garage and they work well with me.

**Comment by HenryDykhne** [comment]
> Hi Henry, actually I am using them right now with the renamed version of tuplan garage and they work well with me.

Are you sure you are using the urbandriver checkpoint? The two most recent ones work fine. The two older ones did not when I tried them.

**Comment by CristianGariboldi** [comment]
I'm sorry, you are right.
The urbandriver checkpoint was the only one that I didn't try and the only one which is not working, the other 3 instead works fine.

**Comment by DanielDauner** [comment]
There is a slight delay with the updated Urban Driver checkpoint due to some technical issues on my side. If you urgently need to run experiments with Urban Driver, consider reverting to the [last repository state before renaming](https://github.com/autonomousvision/tuplan_garage/tree/14eb0447b9db5b0116adb1c2bd368ab5c7ba8aa3). 

Sorry for the delay!

**Comment by HenryDykhne** [comment]
Thankyou for the swift response. Do you mind if I keep this issue open until it gets uploaded?

**Comment by CristianGariboldi** [comment]
I have run the training of urban_driver model with the renamed version of tuplan garage, I attach the pre-trained model here, it should work for the simulation.
[urban_driver.zip](https://github.com/autonomousvision/tuplan_garage/files/13577920/urban_driver.zip)

**Comment by DanielDauner** [comment]
First and foremost, thanks for your patience! 

I have updated the Urban Driver checkpoint in the [Google Drive folder](https://drive.google.com/drive/folders/1LLdunqyvQQuBuknzmf7KMIJiA2grLYB2?usp=sharing
). The updated Val14 numbers are:

| **Method**        | **CLS-R ↑** | **CLS-NR ↑** | **OLS ↑**  |
|-------------------|------------|--------------|------------|
| Urban Driver | 50         | 53           | 81         |
| Urban Driver (deprecated) | 50         | 53           | 82         |

I haven’t evaluated the checkpoint of @CristianGariboldi. I assume the results should be similar. Though thanks for providing your checkpoint!
