### ISSUE TITLE
ROS bridge for real vehicle implementation

### ISSUE THREAD

**Issue by CristianGariboldi** [autonomousvision/tuplan_garage#26]
Hi, I was wondering if you have tried to implement this learning-based planner on a real vehicle, or if you have tried to build a bridge to connect the simulator with a ROS environment.
If that's the case, could you please provide more information about it?
I think it would be very interesting to test this model on a real vehicle! Thanks

**Comment by DanielDauner** [comment]
Hi @CristianGariboldi 

Thank you for your interest in our project!

Currently, we have not implemented our planners on real vehicles. Conducting real-world experiments would necessitate access to a vehicle and a sophisticated perception system for planner inputs, such as HD-Maps and bounding boxes. This falls outside the scope of our current research. The main takeaways of our paper are still valid in my opinion. For instance, rule-based planners like `PDM-Closed` demonstrate robustness in closed-loop settings for typical traffic situations, including lane keeping and vehicle following. On the other hand, learned planners trained in open-loop settings might not effectively translate to closed-loop driving scenarios. A planner like `PDM-Open`, which ignores nearby vehicles, is hazardous in real-world conditions.

There are studies where planners developed in data-driven simulators were successfully transitioned to real-world experiments. For example, [DriveIRL][1] by Motional trained a planner in nuPlan and then applied it to actual scenarios. Other relevant works include the [Urban Driver][2] paper, with closed-loop training, and the [ChauffeurNet][3] paper.

Regarding a ROS, we haven't developed a bridge to integrate nuPlan with ROS environments. However, there have been discussions and attempts about ROS integration in the [nuplan-devkit issue section](https://github.com/motional/nuplan-devkit/issues?q=ROS). Exploring this could be a valuable addition to the nuPlan project.

Let me know if you need any further details or clarification.

[1]: https://arxiv.org/abs/2206.03004
[2]: https://arxiv.org/abs/2109.13333
[3]: https://arxiv.org/abs/1812.03079

**Comment by CristianGariboldi** [comment]
Thanks @DanielDauner for your answer!
I think I will go in that direction, since my objective is to implement a learning-based planner for a real vehicle, and your hybrid model seems an interesting solution!
I will close the issue

**Comment by jessapinkman** [comment]
hi @DanielDauner , i wonder do you have the code of [DriveIRL](https://arxiv.org/abs/2206.03004), I want to learn something details from code. 
Please let me kown if you have it. Thanks!

**Comment by DanielDauner** [comment]
Hi @jessapinkman, unfortunately, we do not have code for DriveIRL. To my knowledge, the code was not made public. However, we would like to have an inverse RL baseline in tuplan Garage in the future.

**Comment by jessapinkman** [comment]
> Hi @jessapinkman, unfortunately, we do not have code for DriveIRL. To my knowledge, the code was not made public. However, we would like to have an inverse RL baseline in tuplan Garage in the future.

Ok, if u have implemened please note it in the readme. Wishing you all the best!
