### ISSUE TITLE
The plan for open source code?

### ISSUE THREAD

**Issue by LarryZhangy** [autonomousvision/tuplan_garage#3]
Great work！It helped me a lot！
Could you tell me what is the plan for open source code?
Thank you very much!

**Comment by kashyap7x** [comment]
Thanks for your interest.

We plan to welcome community contributions to nuPlan garage for new results on the Val14 benchmark and the corresponding planner code. We want to make contributing to this project easy and transparent, so we will create a contribution guide after we have released our pre-trained models. The first release (for PDM-Open, PDM-Offset and PDM-Hybrid) is scheduled for this week.

**Comment by LarryZhangy** [comment]
Thanks for your response.

I'm very interested in contributing to this project and looking forward to seeing the contribution guidelines！
I wonder if there are any candidate papers for the Val14 benchmark ?

**Comment by Syzygianinfern0** [comment]
From https://arxiv.org/abs/2302.07753, it looks like Urban Driver has much better performance metrics as compared to IDM. But it is not that way in your paper. Is there a reason to it?

**Comment by LarryZhangy** [comment]
I want to  contribute to this project, but i dont know which algorithm(from some paper) is worth to be Implemented.

**Comment by kashyap7x** [comment]
@Syzygianinfern0: Urban Driver (like all other learned methods) is great at open-loop ego-forecasting, which is the primary focus in the evaluations in Marcel's earlier paper https://arxiv.org/abs/2302.07753
It is the same in our paper: the OLS (Open Loop Score) metric of Urban Driver is 76, compared to 38 for IDM (Table 2). See Section 4 for an explanation of why the CLS and OLS metrics are not aligned.

@LarryZhangy: we are still in the process of finalizing the contribution guide, please be patient and we will release it soon! I don't have a concrete suggestion for which paper is worth most to implement. Some interesting candidates could be PlanT (https://www.katrinrenz.de/plant/) or any of the nuPlan challenge submissions that placed 2nd to 4th (https://opendrivelab.com/AD23Challenge.html#nuplan_planning)

**Comment by Syzygianinfern0** [comment]
Is there an estimated timeline on the visualization scripts?

**Comment by DanielDauner** [comment]
@Syzygianinfern0 Adding the visualization scripts is not our highest priority at the moment. However, you can visualize our planners using the nuBoard from nuPlan’s devkit.

**Comment by mh0797** [comment]
Update:
We just merged the initial version of our contribution guidelines (see [here](https://github.com/autonomousvision/nuplan_garage/blob/main/CONTRIBUTING.md))
Hence, I am closing this issue.

Feel free to reopen if the guidelines do not answer all of your questions.
