### ISSUE TITLE
Some errors feedback

### ISSUE THREAD

**Issue by dutjyf** [autonomousvision/tuplan_garage#32]
Dear Author

I want to make some suggestions.When run bash file located

`/home/wjl/jyf/tuplan_garage/scripts/simulation/sim_gc_pgp.sh`

I met error `mismatched input '=' expecting <EOF>`

![image](https://github.com/autonomousvision/tuplan_garage/assets/102398709/a1ed5711-4461-45fe-b069-502ff85fed23)

After many attempts I realized that the problem is checkpoint path 

`"/home/wjl/jyf/nuplandata/exp/exp/training_gc_pgp_model/training_gc_pgp_model/2023.12.12.09.53.38/checkpoints/epoch=1.ckpt"`

When I delete the `'='`and rename the checkpoint file , this bash file can run correctly. This code name `epoch=<int>` initially. So I suggest name checkpoint file like`epoch-<int>`

**APPENDIX**

**error shell**

```Bash
SPLIT=val14_split
CHALLENGE=closed_loop_reactive_agents # open_loop_boxes, closed_loop_nonreactive_agents, closed_loop_reactive_agents
CHECKPOINT_PATH="/home/wjl/jyf/nuplandata/exp/exp/training_gc_pgp_model/training_gc_pgp_model/2023.12.12.09.53.38/checkpoints/epoch=1.ckpt" 

python $NUPLAN_DEVKIT_ROOT/nuplan/planning/script/run_simulation.py \
+simulation=$CHALLENGE \
planner=ml_planner \
scenario_filter=$SPLIT \
scenario_builder=nuplan \
planner.ml_planner.model_config='\${model}' \
planner.ml_planner.checkpoint_path=$CHECKPOINT_PATH \
model=gc_pgp_model \
model.aggregator.pre_train=false \
hydra.searchpath="[pkg://tuplan_garage.planning.script.config.common, pkg://tuplan_garage.planning.script.config.simulation, pkg://nuplan.planning.script.config.common, pkg://nuplan.planning.script.experiments]"

```

**correct shell**

```Bash
SPLIT=val14_split
CHALLENGE=closed_loop_reactive_agents # open_loop_boxes, closed_loop_nonreactive_agents, closed_loop_reactive_agents
CHECKPOINT_PATH="/home/wjl/jyf/nuplandata/exp/exp/training_gc_pgp_model/training_gc_pgp_model/2023.12.12.09.53.38/checkpoints/epoch1.ckpt"  #delete '='

python $NUPLAN_DEVKIT_ROOT/nuplan/planning/script/run_simulation.py \
+simulation=$CHALLENGE \
planner=ml_planner \
scenario_filter=$SPLIT \
scenario_builder=nuplan \
planner.ml_planner.model_config='\${model}' \
planner.ml_planner.checkpoint_path=$CHECKPOINT_PATH \
model=gc_pgp_model \
model.aggregator.pre_train=false \
hydra.searchpath="[pkg://tuplan_garage.planning.script.config.common, pkg://tuplan_garage.planning.script.config.simulation, pkg://nuplan.planning.script.config.common, pkg://nuplan.planning.script.experiments]"
```
Best whishes
Yifan

**Comment by mh0797** [comment]
Hi @dutjyf,
Thanks for using our tuplan_garage project!

The checkpoint names are set in nuPlans checkpoint callback [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/training/callbacks/checkpoint_callback.py#L37). If you want to remove the `=` character, you can modify the filename there.

However, a simple solution for your error is to just mask the `=` in your bash file by replacing it with `\=`, i.e., `CHECKPOINT_PATH="/home/wjl/jyf/nuplandata/exp/exp/training_gc_pgp_model/training_gc_pgp_model/2023.12.12.09.53.38/checkpoints/epoch\=1.ckpt" 
`

Best
Marcel

**Comment by dutjyf** [comment]
Thank you for your patient answer! I forgot the escape characters. I hope we can communicate more on issue in the future！
