### ISSUE TITLE
Centerline and States encoding for PDM_Open and PDM_Offset models

### ISSUE THREAD

**Issue by CristianGariboldi** [autonomousvision/tuplan_garage#41]
Hello,
I have a doubt regarding the encoding process of the centerline and the states of the ego: 

**1) Centerline:** from my understanding, you first extract the centerline using Dijkstra, from the starting position to the goal position.
Afterwards, you just keep a length of 120m sampled at 1m and you pass it to the neural network.
My question is: how do you select the "local" centerline of 120m? Is its starting point the same as the ego vehicle for each frame? Or do you implement another logic?

Moreover, each state of the centerline only includes x, y and theta, but in which reference frame?

**2) Ego states:** ego_position, ego_velocity and ego_acceleration have 11 elements (the last one is the present one and the first 10 are the past ones), each with 3 states (x, y and theta). Also in this case, which is the reference frame?

I guess it's the local one, but I ask you just to make sure.

Thank you very much in advance!

**Comment by DanielDauner** [comment]
Hi @CristianGariboldi 

Let’s get to your questions.

(1) Centerline: Given the centerline, we interpolate along the line at every iteration with 1m steps for 120m starting from the ego rear axle pose. Consequently, we convert the interpolated poses into relative coordinates of the ego rear axle. 

(2) Ego States: The positions are again in the coordinate frame of the current rear axle pose. Velocity and acceleration have “x” and “y” in forward and sideway directions, respectively, in the local frame of each timestep. 

Have a look at this [section of the code](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/training/preprocessing/feature_builders/pdm_feature_builder.py#L168), where the PDM features are computed.

**Comment by CristianGariboldi** [comment]
Hi @DanielDauner , thank you so much for your exhaustive answer!

May I ask why the output trajectory of the multilayer perceptron instead only contains 16 poses? 
and how do you extend this trajectory to the whole planning horizon?

**Comment by DanielDauner** [comment]
`PDM-Open` and `PDM-Offset` have a planning horizon of 8 seconds with a reduced frequency of 2 Hz (or at 0.5s steps). No need to further extend it. We never experimented with different frequencies though.

**Comment by CristianGariboldi** [comment]
thanks a lot, everything is clear!
