### ISSUE TITLE
Val14 Dataset

### ISSUE THREAD

**Issue by varunjammula** [autonomousvision/tuplan_garage#42]
Hi,

Are there any plans to release the Val14 dataset to the public or the logic used to split the dataset? Thanks in advance.

**Comment by mh0797** [comment]
Hi  @varunjammula,

The Val14 split is based on the public nuPlan data.
You can run evaluations on the Val14 split by using our [`val14`  scenario-filter](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/script/config/common/scenario_filter/val14_split.yaml).
Have a look at our simulation scripts (e.g., [here](https://github.com/autonomousvision/tuplan_garage/blob/main/scripts/simulation/sim_pdm_closed.sh)) for an example of how to use it.
