### ISSUE TITLE
Visualization scripts release

### ISSUE THREAD

**Issue by IUNONE** [autonomousvision/tuplan_garage#43]
Thanks for great coding and work! 

I'm wondering if you still have plans to release visualization script to generate videos like the teaser.mp4 file in README. Is this file made from simulation (closed-loop)?

Thanks beforehand for taking the time to consider my question!

**Comment by DanielDauner** [comment]
Hi, yes, we are still planning to release visualization scripts. In fact, we created an adaptation of the nuBoard (from the nuplan-devkit) as part of Kashyaps and my new project, [SLEDGE](https://github.com/autonomousvision/sledge). The new visualization aims to fix issues related to rendering and enable more flexibility. 

It’s not yet determined which repository we will add the visualization to. Regardless, we aim to release the code (including the visualization) in mid-June. In the meantime, all our planners in tuPlan Garage still work fine with nuBoard. Thanks for your patience!

The video in the README is closed-loop non-reactive. Videos can be rendered in nuBoard as well; however, there is a deprecation error when calling the webdriver. I close this issue for now, but feel free to ask if you have further questions!
