### ISSUE TITLE
Train data and val14 data

### ISSUE THREAD

**Issue by ZhengYinan-AIR** [autonomousvision/tuplan_garage#46]
Hi, great work!

if the train and val data are combined according to the official data setup method of nuplan, will there be a situation where the data from val14 is trained during the training process, causing the data used for testing to have been seen by the model?

**Comment by DanielDauner** [comment]
Thanks for your interest!

The validation samples are used in the training loop, but only to calculate metrics and visualize samples on held out data. The is no situation where models are trained on frames from Val14. See also Issue #22 (see [here](https://github.com/autonomousvision/tuplan_garage/issues/22#issuecomment-1817586671)) for further information.

Best,
Daniel
