### ISSUE TITLE
about visualization

### ISSUE THREAD

**Issue by SupOne11** [autonomousvision/tuplan_garage#47]
Thank you for open-sourcing your work. How can I export high-resolution simulation images from NuBoard in SVG or other formats? If I use the save button provided by NuBoard, the quality of the images obtained is very poor.

**Comment by DanielDauner** [comment]
Thanks for your interest in our project. 

From my experience with the nuBoard, there are two things you can modify in the nuplan-devkit code regarding your issue. (1) You can modify the plot resolution, as done [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/nuboard/style.py#L31-L32), or (2) you can export individual frames as svg from bokeh (plotting library in nuBoard), somewhere [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/nuboard/base/simulation_tile.py#L457). Maybe this [bokeh documentation](https://docs.bokeh.org/en/latest/docs/reference/io.html) is helpful. The nuBoard default is `get_screenshot_as_png`.

I hope that helps! 

Best Regards,
Daniel

**Comment by SupOne11** [comment]
@DanielDauner Thank you very much for your explanation. I will try according to the part of the bokeh documentation you mentioned. Thank you again.
