### ISSUE TITLE
default_simulation planner

### ISSUE THREAD

**Issue by hu-hwb** [autonomousvision/tuplan_garage#48]
In 'default_simulation': Could not find 'planner/pdm_closed_planner'

Available options in 'planner':
	idm_planner
	log_future_planner
	ml_planner
	remote_planner
	simple_planner

dealed with file:///home/***/tuplan_garage/tuplan_garage/planning/script/config/common

**Comment by hu-hwb** [comment]
Also in training:
/hydra/_internal/config_loader_impl.py:213: UserWarning: provider=hydra.searchpath in command-line, path=tuplan_garage.planning.script.experiments is not available.
  warnings.warn(
In 'default_training': Could not find 'training/training_pdm_offset_model'

Available options in 'training':
	training_raster_model
	training_simple_vector_model
	training_urban_driver_open_loop_model
	training_vector_model

**Comment by hu-hwb** [comment]
I found it is because the wrong of hydra.searchpath="[pkg://tuplan_garage.tuplan_garage.planning.script.config.common,

how to set the hydra.searchpath

**Comment by hu-hwb** [comment]
Another issue:Error instantiating 'nuplan.planning.scenario_builder.nuplan_db.nuplan_scenario_builder.NuPlanScenarioBuilder' : Expected db load path to be file

which dataset should be download and which dir to put

**Comment by mh0797** [comment]
Hi @hu-hwb,
The pdm_closed_planner config should be available if tuplan garage is installed correctly. Please make sure to install it as editable package into your environment (`pip install -e .`)

The second error indicates that you either haven't set the environment variables pointing to the dataset correctly, or that you are missing the trainval split. Please set up the dataset as described [here](https://github.com/motional/nuplan-devkit/blob/master/docs/dataset_setup.md) and set the following [env variables](https://github.com/motional/nuplan-devkit/blob/master/docs/installation.md)

**Comment by hu-hwb** [comment]
> Hi @hu-hwb, The pdm_closed_planner config should be available if tuplan garage is installed correctly. Please make sure to install it as editable package into your environment (`pip install -e .`)
> 
> The second error indicates that you either haven't set the environment variables pointing to the dataset correctly, or that you are missing the trainval split. Please set up the dataset as described [here](https://github.com/motional/nuplan-devkit/blob/master/docs/dataset_setup.md) and set the following [env variables](https://github.com/motional/nuplan-devkit/blob/master/docs/installation.md)



Thank you for your prompt reply. The first question is due to an issue with setting the path for hydra. searchpath, which has been approved file:///home/hwb/tuplan_garage/tuplan_garage/planning/script/config/common solve; Thank you for prompting me to set the environment variable for dataset, so that I can promptly identify the problem

**Comment by DanielDauner** [comment]
Hi @hu-hwb, I am closing this issue for now. Feel free to re-open, if you have further questions!
