### ISSUE TITLE
Confused about the checkpoint

### ISSUE THREAD

**Issue by night3759** [autonomousvision/tuplan_garage#49]
Thank you for open-sourcing your work. I am a little confused that I didn't download any checkpoint you mentioned in the readme. But I ran the example pdm_closed_planner, no error occurred. Is this because this method is totally rule-based? But it seems there are some networks in this algorithm.

**Comment by DanielDauner** [comment]
Yes exactly! PDM-Closed does not have any learned component. Note that PDM-Hybrid (e.g. from the main Figure of the [CoRL paper](https://arxiv.org/abs/2306.07962)) has a learned PDM-Offset module. Also, we provide checkpoints for PDM-Open and GC-PGP [here](https://drive.google.com/drive/folders/1LLdunqyvQQuBuknzmf7KMIJiA2grLYB2?usp=sharing).

Best regards,
Daniel

**Comment by may210297** [comment]
Hello, @DanielDauner , when I directly run the script named 'sim_pdm_closed.sh', the assertion error occurred, i.e. "**AssertionError: AbstractPDMPlanner: Drivable area map must be initialized first!**". 
What confused me is that I did not do any changes to your code and config named nuplan.yaml, can you help me? Thanks very lot!
