### ISSUE TITLE
Problems about the histograms and scenarios of nuboard 

### ISSUE THREAD

**Issue by zc645080234** [autonomousvision/tuplan_garage#51]
When I lauch the run_nuboard.py and upload .nuboard files, I could get the overview metrics but the histograms、scenarios get nothing, which say no simulation data, please add more experiments or adjust the search filter.

I have tried many ways, for examples, serveral times for simulation, adjust the path in nuboard, change the scenario_filter and scenario_builder, change the db root. Unfortunately, none of the methods work, similarly I find the problem https://github.com/motional/nuplan-devkit/issues/368

Could you give me some suggestions? I appreciated it very much!

**Comment by DanielDauner** [comment]
Hi @zc645080234 

I don’t know the exact problem. But I suspect it has something to do with the file paths of your experiment folder (with the `.nuboard` file). I previously had similar issues, if the file paths changed after the simulation was complete. Or if I ran the simulation on a cluster and tried to locally open nuBoard on a mounted directory.

For some reason, the nuBoard fails when changing the simulation folder directory. I suspect the code caches absolute paths somewhere in the simulation logs. 

Did you change the file path of your folder after the simulation? Could you try to simulate and open nuBoard both locally?  

Best,
Daniel

**Comment by zc645080234** [comment]
The rapidity of your answer surprised me very much. I am very grateful for your enthusiasm @DanielDauner 

I ran the simulation and open nuboard locally,  or  I change the path but using the below code to change absolute paths.
I have printed .nuboard file, and get:
NuboardFile(simulation_main_path='/mnt/closed_loop_nonreactive_agents/test14-random', metric_main_path='/mnt/closed_loop_nonreactive_agents/test14-random', metric_folder='metrics', aggregator_metric_folder='aggregator_metric', simulation_folder='simulation_log', current_path=None)



import argparse
from pathlib import Path

from nuplan.planning.nuboard.base.data_class import NuBoardFile

parser = argparse.ArgumentParser(description="Correct NuBoard file.")
parser.add_argument(
    "--root", type=str, help="Root path of the NuBoard file.", required=True
)

args = parser.parse_args()

root = Path(args.root)
nuboard_files = root.rglob("*.nuboard")

for file in nuboard_files:
    nuboard_file = NuBoardFile.load_nuboard_file(file)
    nuboard_file.simulation_main_path = str(file.parent)
    nuboard_file.metric_main_path = str(file.parent)
    save_path = file.parent / "corrected.nuboard"
    nuboard_file.save_nuboard_file(save_path)

**Comment by zc645080234** [comment]
I could find histograms(summary.pdf) in filefold summary, and histograms page display a checkbox(imitation planner) with no data. Scenarios page only show no data

**Comment by DanielDauner** [comment]
Hi @zc645080234, Do you still have this Issue? Do you use regular nuplan-devkit and tuplan Garage code?

Best,
Daniel

**Comment by zc645080234** [comment]
> Hi @zc645080234, Do you still have this Issue? Do you use regular nuplan-devkit and tuplan Garage code?
> 
> Best, Daniel

I have tried other method to visualize the simulation, thank u~

**Comment by LeoRepeater** [comment]
> > Hi @zc645080234, Do you still have this Issue? Do you use regular nuplan-devkit and tuplan Garage code?
> > Best, Daniel
> 
> I have tried other method to visualize the simulation, thank u~

hi @zc645080234 ,happy to see you have visualise the simulation .I have same problems and could you please share the method? I appreciated it very much!
