### ISSUE TITLE
Closed-loop simulation error

### ISSUE THREAD

**Issue by may210297** [autonomousvision/tuplan_garage#52]
Hello, @DanielDauner , when I directly run the script named 'sim_pdm_closed.sh', the assertion error occurred, i.e. "**AssertionError: AbstractPDMPlanner: Drivable area map must be initialized first!**". 
What confused me is that I did not do any changes to your code and config named nuplan.yaml, can you help me? Thanks very lot!

**Below is my dataset structure**:
~/nuplan/dataset:
├── maps
│   ├── nuplan-maps-v1.0.json
│   ├── sg-one-north
│   ├── us-ma-boston
│   ├── us-nv-las-vegas-strip
│   └── us-pa-pittsburgh-hazelwood
├── nuplan-v1.1
│   ├── splits
│   ├── test
│   └── trainval

**ERROR details**:
![image](https://github.com/user-attachments/assets/a534ede3-4a03-4e30-a371-f4369fa9d50d)

**Comment by DanielDauner** [comment]
Hi @may210297 

This issue already occurred in #45, but it wasn't resolved. For some reason, the drivable area map is `None`. Maybe some general points to trace the error source:

- Do other planners (e.g. IDM) work fine?
- Did you set the [default directories](https://nuplan-devkit.readthedocs.io/en/latest/installation.html#change-default-directories)?
- `trainval` and `test` need to be in `/dataset/nuplan-v1.1/splits`. Could this affect the issue?

Best,
Daniel

**Comment by may210297** [comment]
Thanks for your quick reply! @DanielDauner :
I will try to solve the problem according to your advice.
- IDMPlanner can work well in open-loop simulation, but failed in closed-loop simulation with warning 'WARNING:nuplan.planning.simulation.planner.idm_planner:IDMPlanner could not find valid path to the target roadblock. Using longest route found instead'
- I have change the default directories
  ```
  export NUPLAN_DATA_ROOT="~/nuplan/dataset"
  export NUPLAN_MAPS_ROOT="~/nuplan/dataset/maps"
  export NUPLAN_EXP_ROOT="~/nuplan/exp"
  export NUPLAN_DEVKIT_ROOT="~/nuplan-devkit/"
  ```
- I have tried to move the `trainval` into `/dataset/nuplan-v1.1/splits`, but the problem is not solved.

May I have your version of `nuplan-devkit`? Would this can affect your repo?

**Comment by DanielDauner** [comment]
I tried to reproduce the issue, including a new install of `nuplan-devkit`, `tuplan_garage` and the conda environment. On my system, the planner runs without problems.

The native `nuplan-devkit` v1.2.2 should work fine, except for the fix described [here](https://github.com/motional/nuplan-devkit/issues/379).

For some reason, the drivable area map is not loaded, as done [here](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/simulation/planner/pdm_planner/pdm_closed_planner.py#L90). Could you check if the function is correctly called? Does the error occur in a specific scenario? In that case, could you provide the scenario token? 

A few other things:
- Have you made any changes to the code or the `sim_pdm_closed.sh`?
- On what system are you running `nuplan-devkit` and `tuplan_garage`? (e.g. locally or on a server)
- Have you installed `nuplan-devkit` and `tuplan_garage` as editable pip-packages?  (i.e. `pip install -e .`)
- Could you try to re-download the maps?

Best,
Daniel

**Comment by may210297** [comment]
I also modified the `trainval` path like [this](https://github.com/motional/nuplan-devkit/issues/379). 

Besides, no change is to the code `sim_pdm_closed.sh`  as follows and code is running on a Ubuntu remote server.
  ```shell
  # Only the path in nuplan.yaml is modified by me.
  SPLIT=val14_split
  CHALLENGE=closed_loop_reactive_agents # open_loop_boxes, closed_loop_nonreactive_agents, closed_loop_reactive_agents
  
  python $NUPLAN_DEVKIT_ROOT/nuplan/planning/script/run_simulation.py \
  +simulation=$CHALLENGE \
  planner=pdm_closed_planner \
  scenario_filter=$SPLIT \
  scenario_builder=nuplan \
  hydra.searchpath="[pkg://tuplan_garage.planning.script.config.common, pkg://tuplan_garage.planning.script.config.simulation, pkg://nuplan.planning.script.config.common, pkg://nuplan.planning.script.experiments]"
  ```
`nuplan-devkit` and `tuplan_garage` are already installed and I re-download the `nuplan-maps-v1.0` the problem still exists, and the drivable area map only exists in the path `us-nv-las-vegas-strip/9.15.1915/drivable_area.npy.npz` before and after. 

I noticed the driveable area map [here ](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/simulation/planner/pdm_planner/pdm_closed_planner.py#L90), so I set checkpoint here when  running the code: The `intersecting_lanes ` [here](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/simulation/planner/pdm_planner/abstract_pdm_planner.py#162) is printed, it will be `[]` after several iterations in every simulation, such as `[2021.09.14.17.35.14_veh-45_00520_01008, 2e35d8043dfc57ac]`.

**Comment by DanielDauner** [comment]
Strange issue. I still wasn't able to reproduce this given the scenario you provided. 

From what I can tell, the assertion either fails if 
- (1) `self._drivable_area_map is None` or 
- (2) `len(self._drivable_area_map) == 0`. 

Could you tell me, what is the case? 

(1) would hint a loading error of the `map_api`. (2) would indicate no map elements were found in a 50m radius. 

Weirdly, neither (1) or (2) should happen.

Edit: The driveable area map in my folder is only provided for Las Vegas. I think these files are just alternative raster grids for faster access somewhere in nuPlan's map api. It should work for other maps, regardless.

**Comment by may210297** [comment]
I add the code before assert section,  exactly the `len(self._drivable_area_map) == 0` happens.
```
print(f"{self._drivable_area_map is None, len(self._drivable_area_map) == 0}")
```

Bro, I will try on this next day (I need to sleep in my zone).

**Comment by DanielDauner** [comment]
I guess the code can't find map elements in the nearby area, ie. in [this call](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/simulation/planner/pdm_planner/observation/pdm_observation_utils.py#L28).

- Does that happen in the first iteration?
- Does that happen for specific maps? (e.g. Las Vegas, Boston, Pittsburgh)

**Comment by may210297** [comment]
Almost it occurred in all the maps, but not in the first iteration. I listed the `self._map_api.map_name` and `self._iteration` below. 

```
(wrapped_fn pid=2106353) Invaild drivable area map ('us-ma-boston', 31) [repeated 92x across cluster]
(wrapped_fn pid=2107988) Invaild drivable area map ('sg-one-north', 33) [repeated 90x across cluster]
(wrapped_fn pid=2107354) Invaild drivable area map ('us-nv-las-vegas-strip', 20) [repeated 423x across cluster]
(wrapped_fn pid=2106986) Invaild drivable area map ('us-pa-pittsburgh-hazelwood', 61) [repeated 280x across cluster]
(wrapped_fn pid=2106353) Invaild drivable area map ('us-ma-boston', 62) [repeated 121x across cluster]
(wrapped_fn pid=2106804) Invaild drivable area map ('sg-one-north', 67) [repeated 100x across cluster]
(wrapped_fn pid=2106355) Invaild drivable area map ('us-nv-las-vegas-strip', 59) [repeated 949x across cluster]
(wrapped_fn pid=2106986) Invaild drivable area map ('us-pa-pittsburgh-hazelwood', 91) [repeated 331x across cluster]
(wrapped_fn pid=2106353) Invaild drivable area map ('us-ma-boston', 94) [repeated 125x across cluster]
(wrapped_fn pid=2107275) Invaild drivable area map ('sg-one-north', 95) [repeated 130x across cluster]
(wrapped_fn pid=2106389) Invaild drivable area map ('us-nv-las-vegas-strip', 53) [repeated 1127x across cluster]
(wrapped_fn pid=2106908) Invaild drivable area map ('us-pa-pittsburgh-hazelwood', 121) [repeated 317x across cluster]
(wrapped_fn pid=2106353) Invaild drivable area map ('us-ma-boston', 127) [repeated 135x across cluster]
(wrapped_fn pid=2106804) Invaild drivable area map ('sg-one-north', 130) [repeated 121x across cluster]
(wrapped_fn pid=2106389) Invaild drivable area map ('us-nv-las-vegas-strip', 73) [repeated 1136x across cluster]
(wrapped_fn pid=2106592) Invaild drivable area map ('us-pa-pittsburgh-hazelwood', 144) [repeated 312x across cluster]
(wrapped_fn pid=2106526) Invaild drivable area map ('us-ma-boston', 141) [repeated 88x across cluster]
(wrapped_fn pid=2106752) Invaild drivable area map ('sg-one-north', 144) [repeated 98x across cluster]
(wrapped_fn pid=2107331) Invaild drivable area map ('us-nv-las-vegas-strip', 133) [repeated 1156x across cluster]
```

- I try to print the length of `drivable_area`,`drivable_polygons`,`drivable_polygon_ids` [here](https://github.com/autonomousvision/tuplan_garage/blob/main/tuplan_garage/planning/simulation/planner/pdm_planner/observation/pdm_observation_utils.py#L45) with `print(f'drivable area map {len(drivable_area)}, drivable_polygons, {len(drivable_polygons)}, drivable_polygon_ids, {len(drivable_polygon_ids)}')`.  **This always happened after simultations 0**:
  ```
  (wrapped_fn pid=2385425) ipdb> 
  drivable_area[SemanticMapLayer.ROADBLOCK]
  (wrapped_fn pid=2385425) []
  (wrapped_fn pid=2385425) ipdb> 
  drivable_area[SemanticMapLayer.CARPARK_AREA]
  (wrapped_fn pid=2385425) []
  (wrapped_fn pid=2385425) ipdb> 
  drivable_area[SemanticMapLayer.ROADBLOCK_CONNECTOR]
  (wrapped_fn pid=2385425) []
  ```

**Comment by DanielDauner** [comment]
Interesting. So, the code fails after a few iterations, indicating that the maps are initially loaded and working fine. To be honest, I have no clue what's going on. 

I had a look into the map loading code last night. There are several LRU cache decorators for the map loading functions. I wonder whether the code breaks under a high number of threads, i.e. on your cluster. Could you try to modify the `worker` setting in the bash script? 

- For example, restrict the treads with `worker.threads_per_node=X`. We usually use `X=32` or `X=16`. 
- You can also try a different worker, e.g. add the argument `worker=single_machine_thread_pool` or `worker=sequential`. These will be slow but sometimes more stable.

The map is correctly installed, and most machines' failures don't occur. Therefore, I think the error is related to some nuPlan simulation settings.

**Comment by may210297** [comment]
Yes, I have tried to set `worker.threads_per_node=1` stil helpless, the same as `worker=single_machine_thread_pool` or `worker=sequential`. Too difficult haha.

**Comment by DanielDauner** [comment]
This is a difficult one.

- Does the error also happen for other [challenges](https://github.com/autonomousvision/tuplan_garage/blob/main/scripts/simulation/sim_pdm_closed.sh#L3)?
- Is there any option to run the code on a different machine?

**Comment by may210297** [comment]
Yes, maybe just on this machine. `open_loop_boxes` can run successfully, `closed_loop_nonreactive_agents` and `closed_loop_reactive_agents` will fail while `idm_planner` even can't work.

**Comment by DanielDauner** [comment]
If I understand it correctly, the error might not originate from PDM-Closed directly, as the open-loop evaluation works fine. Only closed-loop is affected. I am running out of ideas.

Does the error occur for different scenario filtering settings? Could you try to run a simulation with very few scenarios (e.g. <5)?

**Comment by may210297** [comment]
Overall, thanks for your great help! If I know the reason I will add it. The error also occurs in challenge `test14-hard`.

**Comment by DanielDauner** [comment]
Sorry we couldn't resolve the issue 🫤. Good luck tho!
