### ISSUE TITLE
nuboard visualization 

### ISSUE THREAD

**Issue by jessapinkman** [autonomousvision/tuplan_garage#54]
hi, @DanielDauner 

When I get the visualization scene through nuboard, the color scheme is not very good, as shown below:
![image](https://github.com/user-attachments/assets/6938ed99-22fc-4b3a-a44e-d066a4d44fda)

How can I configure nuboard to get a rendering scene like yours?
![image](https://github.com/user-attachments/assets/df1ad2a0-7c1a-4c86-94d8-deda2594fd85)

**Comment by mh0797** [comment]
Hi,
please have a look at the answer I posted [here](https://github.com/mh0797/interPlan/issues/4)
