### ISSUE TITLE
Questions about nuplan dataset

### ISSUE THREAD

**Issue by fty2000** [autonomousvision/tuplan_garage#55]
Thank you for the great work! I am new to the field of planning.According to the official data setup method of nuplan, does that mean i need to combine the train split and val split into one folder(trainval)
Thank you so much for your help!
![截图 2024-09-25 20-20-13](https://github.com/user-attachments/assets/e767af4f-2e22-48b1-9960-cb25f829f47f)
![截图 2024-09-25 20-21-36](https://github.com/user-attachments/assets/ccb3286e-b4e2-4a04-b312-a012207434ca)

**Comment by DanielDauner** [comment]
Hi @fty2000. Yes, exactly. The `.db` files from the training and validation split need to be merged into the `trainval` folder. It's slightly confusing. The `test` and `mini` split get their separate folder in the same directory. 

Best,
Daniel

**Comment by fty2000** [comment]
> Hi @fty2000. Yes, exactly. The `.db` files from the training and validation split need to be merged into the `trainval` folder. It's slightly confusing. The `test` and `mini` split get their separate folder in the same directory.你好。是的，没错。需要将训练和验证分割中的 `.db` 文件合并到 `trainval` 文件夹中。这有点令人困惑。`test` 和 `mini` split 在同一目录中获取各自的文件夹。
> 
> Best, 最好 Daniel 丹尼尔

Thank you for your response
