### ISSUE TITLE
The issues of running on the windows

### ISSUE THREAD

**Issue by kongxincaizi** [autonomousvision/tuplan_garage#56]
Thank you so much for this work.  I find it very interesting!

But now I have two questions:
1. Has this work been tested under windows? 
2. If I want to migrate it to windows system, where should I modify it? 

Look forward to your reply, thank you!

**Comment by DanielDauner** [comment]
Thanks for your interest in our project! 

Unfortunately, we haven't tested our repository on a Windows system and can't guarantee that it works off the shelf. Some people seem to have used nuPlan before on a Windows system, based on the [nuPlan issues](https://github.com/motional/nuplan-devkit/issues?q=windows). 

I recommend you give it a try. If you run into dependency issues, you can try to resolve or avoid corresponding libraries.

**Comment by kongxincaizi** [comment]
> Thanks for your interest in our project!
> 
> Unfortunately, we haven't tested our repository on a Windows system and can't guarantee that it works off the shelf. Some people seem to have used nuPlan before on a Windows system, based on the [nuPlan issues](https://github.com/motional/nuplan-devkit/issues?q=windows).
> 
> I recommend you give it a try. If you run into dependency issues, you can try to resolve or avoid corresponding libraries.

Thanks for your reply and suggestions. I will try later.  

And thank you again for opening this repository.  Best wishes!
