### ISSUE TITLE
typing problem of self._drivable_area_map in abstract_pdm_planner.py

### ISSUE THREAD

**Issue by richie-live** [autonomousvision/tuplan_garage#57]
In abstract_pdm_planner.py

`self._drivable_area_map: Optional[PDMPath] = None`
should be
`self._drivable_area_map: Optional[PDMOccupancyMap] = None`

and 
```
from tuplan_garage.planning.simulation.planner.pdm_planner.observation.pdm_occupancy_map import (
    PDMOccupancyMap,
)
```
should be added

Or I get the pylance problem
![image](https://github.com/user-attachments/assets/224818c9-40e1-4020-8058-311f5b676735)

**Comment by DanielDauner** [comment]
Yes, that is correct. We fixed the incorrect type hint. Thanks for mentioning it! 

Best
Daniel
