### ISSUE TITLE
GPU memory usage increase by 20MB every simulation

### ISSUE THREAD

**Issue by richie-live** [autonomousvision/tuplan_garage#60]
Hello, why does my GPU memory usage increase by 20MB every time I simulate a scene while running the simulation? I am using a learning based planner and worker=sequential.

**Comment by DanielDauner** [comment]
Hi Richie,

I assume your code loads the checkpoint onto the GPU for each simulation and doesn’t release the weights from GPU memory. Unfortunately, nuPlan does not have a “close” call for a planner. In other words, the `AbstractPlanner` class does not know when the last iteration is, e.g. to clear memory. You could, in theory, set the [`requires_scenario`](https://github.com/motional/nuplan-devkit/blob/cd3fd8d3d0c4d390fcb74d05fd56f92d9e0c366b/nuplan/planning/simulation/planner/abstract_planner.py#L48) flag to true and based on the scenario class clear the memory once the simulation is over.

Note that performing simulation in `sequential` mode and on the GPU is generally slower. We recommend using `ray_distributed` and leaving the trained model on the CPU. The `sequential` mode makes sense for benchmarking the planner runtime.

I hope that helps! 

Best,
Daniel
